# Generated by Django 5.2.2 on 2025-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_season_event_season'),
        ('main', '0004_musicianprofile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='seasons', to='main.musicianprofile'),
        ),
    ]
