# Generated by Django 5.2.2 on 2025-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_add_musicians_to_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.DecimalField(choices=[(0.0, 'Nieobecny'), (0.5, 'Połowa'), (1.0, 'Obecny')], decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
