# Generated by Django 5.2.2 on 2025-07-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
