# Generated by Django 5.2.2 on 2025-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_musicianprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
