# Generated by Django 5.2.2 on 2025-07-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_concert_musicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='setlist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
