"""
Django settings for oragh_platform project.

Generated by 'django-admin startproject' using Django 5.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&b8%$j5)s#56it58k^d$^zronp6)hmv54q#gh%ogyju-9hp@2*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'register',
    'concerts',
    'crispy_forms',
    'crispy_bootstrap5',
    'attendance',
    'forum',
    'django_ckeditor_5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'oragh_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'oragh_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'oragh_db',
#         'USER': 'krzysiek',
#         'PASSWORD': 'krzysiek',
#         'HOST': 'localhost',  # Or the IP of your PostgreSQL server
#         'PORT': '5432',       # Default PostgreSQL port
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

LANGUAGE_CODE = 'pl' 

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = "/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# CKEditor 5 Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote'],
    },
    'advanced': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|',
            'numberedList', 'bulletedList', 'todoList', '|',
            'indent', 'outdent', '|',
            'link', 'blockQuote', 'insertTable', 'codeBlock', '|',
            'specialCharacters', 'horizontalLine', 'emoji', '|',
            'undo', 'redo'
        ],
        'heading': {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3' },
                { 'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4' }
            ]
        },
        'fontSize': {
            'options': ['tiny', 'small', 'default', 'big', 'huge']
        },
        'fontFamily': {
            'options': [
                'default',
                'Arial, Helvetica, sans-serif',
                'Courier New, Courier, monospace',
                'Georgia, serif',
                'Lucida Sans Unicode, Lucida Grande, sans-serif',
                'Tahoma, Geneva, sans-serif',
                'Times New Roman, Times, serif',
                'Trebuchet MS, Helvetica, sans-serif',
                'Verdana, Geneva, sans-serif'
            ]
        },
        'fontColor': {
            'colors': [
                {'color': 'hsl(0, 0%, 0%)', 'label': 'Black'},
                {'color': 'hsl(0, 0%, 30%)', 'label': 'Dim grey'},
                {'color': 'hsl(0, 0%, 60%)', 'label': 'Grey'},
                {'color': 'hsl(0, 0%, 90%)', 'label': 'Light grey'},
                {'color': 'hsl(0, 0%, 100%)', 'label': 'White', 'hasBorder': True},
                {'color': 'hsl(0, 75%, 60%)', 'label': 'Red'},
                {'color': 'hsl(30, 75%, 60%)', 'label': 'Orange'},
                {'color': 'hsl(60, 75%, 60%)', 'label': 'Yellow'},
                {'color': 'hsl(90, 75%, 60%)', 'label': 'Light green'},
                {'color': 'hsl(120, 75%, 60%)', 'label': 'Green'},
                {'color': 'hsl(150, 75%, 60%)', 'label': 'Aquamarine'},
                {'color': 'hsl(180, 75%, 60%)', 'label': 'Turquoise'},
                {'color': 'hsl(210, 75%, 60%)', 'label': 'Light blue'},
                {'color': 'hsl(240, 75%, 60%)', 'label': 'Blue'},
                {'color': 'hsl(270, 75%, 60%)', 'label': 'Purple'},
            ]
        },
        'fontBackgroundColor': {
            'colors': [
                {'color': 'hsl(0, 75%, 60%)', 'label': 'Red'},
                {'color': 'hsl(30, 75%, 60%)', 'label': 'Orange'},
                {'color': 'hsl(60, 75%, 60%)', 'label': 'Yellow'},
                {'color': 'hsl(90, 75%, 60%)', 'label': 'Light green'},
                {'color': 'hsl(120, 75%, 60%)', 'label': 'Green'},
                {'color': 'hsl(150, 75%, 60%)', 'label': 'Aquamarine'},
                {'color': 'hsl(180, 75%, 60%)', 'label': 'Turquoise'},
                {'color': 'hsl(210, 75%, 60%)', 'label': 'Light blue'},
                {'color': 'hsl(240, 75%, 60%)', 'label': 'Blue'},
                {'color': 'hsl(270, 75%, 60%)', 'label': 'Purple'},
            ]
        },
        'alignment': {
            'options': ['left', 'center', 'right', 'justify']
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells', 'tableProperties', 'tableCellProperties']
        },
        'specialCharacters': {
            'options': [
                {'title': 'Arrows', 'items': ['←', '↑', '→', '↓', '↔', '↕', '↖', '↗', '↘', '↙', '↺', '↻']},
                {'title': 'Mathematical', 'items': ['±', '×', '÷', '=', '≠', '≤', '≥', '∞', '∑', '∏', '∆', '√', '∂', '∫', '≈', '≡', '∝', '∴', '∵', '∈', '∉', '⊂', '⊃', '⊄', '⊅', '∩', '∪']},
                {'title': 'Currency', 'items': ['$', '€', '£', '¥', '₹', '₽', '₩', '₪', '₴', '₦', '₡', '₨', '₵', '₸', '₼', '₺']},
                {'title': 'Latin', 'items': ['Á', 'À', 'Ă', 'Â', 'Å', 'Ä', 'Ã', 'Ą', 'Ā', 'á', 'à', 'ă', 'â', 'å', 'ä', 'ã', 'ą', 'ā', 'É', 'È', 'Ĕ', 'Ê', 'Ě', 'Ë', 'Ė', 'Ę', 'Ē', 'é', 'è', 'ĕ', 'ê', 'ě', 'ë', 'ė', 'ę', 'ē', 'Í', 'Ì', 'Ĭ', 'Î', 'Ï', 'İ', 'Į', 'Ī', 'í', 'ì', 'ĭ', 'î', 'ï', 'į', 'ī', 'Ó', 'Ò', 'Ŏ', 'Ô', 'Ö', 'Õ', 'Ő', 'Ø', 'Ō', 'ó', 'ò', 'ŏ', 'ô', 'ö', 'õ', 'ő', 'ø', 'ō', 'Ú', 'Ù', 'Ŭ', 'Û', 'Ů', 'Ü', 'Ű', 'Ų', 'Ū', 'ú', 'ù', 'ŭ', 'û', 'ů', 'ü', 'ű', 'ų', 'ū']},
                {'title': 'Polish', 'items': ['Ą', 'Ć', 'Ę', 'Ł', 'Ń', 'Ó', 'Ś', 'Ź', 'Ż', 'ą', 'ć', 'ę', 'ł', 'ń', 'ó', 'ś', 'ź', 'ż']},
                {'title': 'Emojis', 'items': ['😀', '😃', '😄', '😁', '😅', '😂', '🤣', '😊', '😇', '🙂', '😉', '😍', '🥰', '😘', '😋', '😛', '😎', '🤩', '😏', '😞', '😢', '😭', '😤', '😠', '😡', '🤬', '😱', '😨', '🤗', '🤔', '🙄', '😴', '🤤', '😷', '🤒', '🤕', '👍', '👎', '👏', '🙌', '👐', '🤝', '🙏', '✌️', '🤞', '🤟', '🤘', '👌', '🤏', '💪', '❤️', '🧡', '💛', '💚', '💙', '💜', '🖤', '🤍', '💯', '💢', '💥', '💫', '💦', '💨']},
                {'title': 'Punctuation', 'items': ['…', '–', '—', ''', ''', '"', '"', '‚', '„', '‹', '›', '«', '»', '‡', '†', '•', '‰', '‱', '′', '″', '‴', '§', '¶', '©', '®', '™', '℠']},
            ]
        },
        'image': {
            'toolbar': []
        },
        'height': 350,
        'width': '100%',
    }
}
