# Generated by Django 5.2.2 on 2025-06-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='musicians',
            field=models.ManyToManyField(blank=True, related_name='concerts', to='main.musicianprofile'),
        ),
    ]
