# Generated by Django 5.2.2 on 2025-07-24 21:36

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_concert_setlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='setlist',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Setlist'),
        ),
    ]
