# Generated by Django 5.2.2 on 2025-08-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0004_alter_concert_description_alter_concert_setlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(),
        ),
    ]
