# Generated by Django 5.2.2 on 2025-09-02 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nazwa")),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("board", "Tylko board"),
                            ("all", "Wszyscy użytkownicy"),
                        ],
                        default="all",
                        max_length=10,
                        verbose_name="Poziom dostępu",
                    ),
                ),
                (
                    "highlight_style",
                    models.CharField(
                        choices=[
                            ("none", "Brak wyróżnienia"),
                            ("management", "Dział board - niebieski"),
                            ("orchestra", "Dział orkiestry - zielony"),
                            ("entertainment", "Dział rozrywki - pomarańczowy"),
                            ("important", "Ważne - czerwony"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Styl wyróżnienia",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Kolejność")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdirectories",
                        to="forum.directory",
                        verbose_name="Katalog nadrzędny",
                    ),
                ),
            ],
            options={
                "verbose_name": "Katalog",
                "verbose_name_plural": "Katalogi",
                "db_table": "forum_directory",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("content", models.TextField(verbose_name="Treść")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="Przypięty"),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Zablokowany"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "directory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="forum.directory",
                        verbose_name="Katalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post",
                "verbose_name_plural": "Posty",
                "db_table": "forum_post",
                "ordering": ["-is_pinned", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Treść")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(default=False, verbose_name="Edytowany"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="forum.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komentarz",
                "verbose_name_plural": "Komentarze",
                "db_table": "forum_comment",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("content", models.TextField(verbose_name="Treść")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywne"),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Priorytet")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ogłoszenie",
                "verbose_name_plural": "Ogłoszenia",
                "db_table": "forum_announcement",
                "ordering": ["-priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-priority", "-created_at"],
                        name="forum_annou_is_acti_53cb20_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(
                fields=["parent", "order", "name"],
                name="forum_direc_parent__9fb8cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(
                fields=["access_level"], name="forum_direc_access__962c45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="directory",
            index=models.Index(
                fields=["author"], name="forum_direc_author__fadc4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["directory", "-is_pinned", "-updated_at"],
                name="forum_post_directo_3d07e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["author", "-created_at"], name="forum_post_author__f7ff0a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-created_at"], name="forum_post_created_543ce4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "created_at"], name="forum_comme_post_id_02253c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["author", "-created_at"], name="forum_comme_author__f95930_idx"
            ),
        ),
    ]
