# Generated by Django 5.2.2 on 2025-09-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='access_level',
            field=models.CharField(choices=[('all', 'Wszyscy'), ('board', 'Tylko board')], default='all', max_length=10, verbose_name='Poziom dostępu'),
        ),
        migrations.AlterField(
            model_name='directory',
            name='highlight_style',
            field=models.CharField(choices=[('none', 'Normalny'), ('management', 'Dział board - niebieski'), ('orchestra', 'Orkiestra - zielony'), ('entertainment', 'Rozrywka - pomarańczowy'), ('important', 'Ważne - czerwony')], default='none', max_length=20, verbose_name='Styl wyróżnienia'),
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
