# Generated by Django 5.2.2 on 2025-09-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_alter_directory_access_level_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "ordering": ["created_at"],
                "permissions": [
                    ("can_moderate_comments", "Can moderate all forum comments")
                ],
                "verbose_name": "Komentarz",
                "verbose_name_plural": "Komentarze",
            },
        ),
        migrations.AlterModelOptions(
            name="directory",
            options={
                "ordering": ["order", "name"],
                "permissions": [
                    ("can_create_directory", "Can create forum directories"),
                    ("can_manage_directories", "Can manage all forum directories"),
                ],
                "verbose_name": "Katalog",
                "verbose_name_plural": "Katalogi",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-is_pinned", "-updated_at"],
                "permissions": [
                    ("can_pin_posts", "Can pin forum posts"),
                    ("can_lock_posts", "Can lock forum posts"),
                    ("can_moderate_posts", "Can moderate all forum posts"),
                ],
                "verbose_name": "Post",
                "verbose_name_plural": "Posty",
            },
        ),
    ]
