# Generated by Django 5.2.2 on 2025-08-26 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('setlist', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planowany'), ('confirmed', 'Potwierdzony'), ('completed', 'Zakończony'), ('cancelled', 'Odwołany')], default='planned', max_length=20)),
                ('is_public', models.BooleanField(default=True, help_text='Czy koncert jest publiczny')),
                ('registration_open', models.BooleanField(default=True, help_text='Czy rejestracja na koncert jest otwarta')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maksymalna liczba uczestników', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerts_created', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='concerts', to='users.musicianprofile')),
            ],
            options={
                'db_table': 'concerts_concert',
                'ordering': ['-date', '-date_created'],
            },
        ),
    ]
