# Generated by Django 5.2.2 on 2025-08-26 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0001_initial'),
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['date'], name='concerts_co_date_be5ed1_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['status'], name='concerts_co_status_f84e34_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['is_public', 'registration_open'], name='concerts_co_is_publ_cebc4a_idx'),
        ),
        migrations.AddIndex(
            model_name='concert',
            index=models.Index(fields=['created_by'], name='concerts_co_created_617c4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='concert',
            constraint=models.CheckConstraint(condition=models.Q(('max_participants__isnull', True), ('max_participants__gt', 0), _connector='OR'), name='concerts_max_participants_positive'),
        ),
    ]
