# Generated by Django 5.2.2 on 2025-08-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0002_concert_concerts_co_date_be5ed1_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concert",
            options={"ordering": ["date", "date_created"]},
        ),
    ]
