# Generated by Django 5.2.2 on 2026-02-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concerts", "0003_alter_concert_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="concert",
            options={
                "ordering": ["date", "date_created"],
                "verbose_name": "Koncert",
                "verbose_name_plural": "Koncerty",
            },
        ),
        migrations.RemoveConstraint(
            model_name="concert",
            name="concerts_max_participants_positive",
        ),
        migrations.RemoveIndex(
            model_name="concert",
            name="concerts_co_is_publ_cebc4a_idx",
        ),
        migrations.RemoveField(
            model_name="concert",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="concert",
            name="max_participants",
        ),
        migrations.RemoveField(
            model_name="concert",
            name="registration_open",
        ),
    ]
