# Generated by Django 5.2.2 on 2025-08-27 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 2024/2025", max_length=20, unique=True
                    ),
                ),
                ("start_date", models.DateField(help_text="Start date of the season")),
                ("end_date", models.DateField(help_text="End date of the season")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this season is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "musicians",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attendance_seasons",
                        to="users.musicianprofile",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_season",
                "ordering": ["-start_date"],
                "permissions": [("manage_seasons", "Can manage seasons")],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("concert", "Koncert"),
                            ("rehearsal", "Próba"),
                            ("soundcheck", "Soundcheck"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="attendance.season",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_event",
                "ordering": ["date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "present",
                    models.DecimalField(
                        choices=[(0.0, "Nieobecny"), (0.5, "Połowa"), (1.0, "Obecny")],
                        decimal_places=1,
                        default=0.0,
                        max_digits=3,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_marks_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="attendance.event",
                    ),
                ),
            ],
            options={
                "db_table": "attendance_attendance",
                "indexes": [
                    models.Index(
                        fields=["user", "event"], name="attendance__user_id_03a5ca_idx"
                    ),
                    models.Index(
                        fields=["present"], name="attendance__present_b77c6b_idx"
                    ),
                    models.Index(
                        fields=["event"], name="attendance__event_i_d78a6f_idx"
                    ),
                ],
                "unique_together": {("user", "event")},
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="attendance__date_bb5a26_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["type"], name="attendance__type_e4c258_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["season"], name="attendance__season__e2ba5b_idx"
            ),
        ),
    ]
