# Generated by Django 5.2.2 on 2025-09-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this season is currently active'),
        ),
    ]
