# Generated by Django 5.2.2 on 2026-02-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_move_season_to_seasons_app"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={"verbose_name": "Obecność", "verbose_name_plural": "Obecności"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["date", "created_at"],
                "verbose_name": "Wydarzenie",
                "verbose_name_plural": "Wydarzenia",
            },
        ),
    ]
