# Generated by Django 5.2.2 on 2025-07-10 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 2024/2025', max_length=20, unique=True)),
                ('start_date', models.DateField(help_text='Start date of the season')),
                ('end_date', models.DateField(help_text='End date of the season')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this season is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
                'permissions': [('manage_seasons', 'Can manage seasons')],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='attendance.season'),
        ),
    ]
