# Generated by Django 5.2.2 on 2025-08-27 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MusicianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instrument",
                    models.CharField(
                        choices=[
                            ("flet", "Flet"),
                            ("klarnet", "Klarnet"),
                            ("obój", "Obój"),
                            ("saksofon", "Saksofon"),
                            ("waltornia", "Waltornia"),
                            ("eufonium", "Eufonium"),
                            ("trąbka", "Trąbka"),
                            ("puzon", "Puzon"),
                            ("tuba", "Tuba"),
                            ("fagot", "Fagot"),
                            ("gitara", "Gitara"),
                            ("perkusja", "Perkusja"),
                        ],
                        max_length=20,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "main_musicianprofile",
            },
        ),
    ]
