# Generated by manual migration
from django.db import migrations


def update_contenttypes(apps, schema_editor):
    """
    Update ContentType for Event and Attendance models from 'attendance' to 'seasons' app.
    This is needed because these models were moved from attendance app to seasons app.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Update Event ContentType
    try:
        event_ct = ContentType.objects.get(app_label='attendance', model='event')
        event_ct.app_label = 'seasons'
        event_ct.save()
        print("✓ Updated Event ContentType from attendance to seasons")
    except ContentType.DoesNotExist:
        print("Event ContentType already updated or doesn't exist")
    
    # Update Attendance ContentType
    try:
        attendance_ct = ContentType.objects.get(app_label='attendance', model='attendance')
        attendance_ct.app_label = 'seasons'
        attendance_ct.save()
        print("✓ Updated Attendance ContentType from attendance to seasons")
    except ContentType.DoesNotExist:
        print("Attendance ContentType already updated or doesn't exist")


def reverse_contenttypes(apps, schema_editor):
    """
    Reverse the ContentType changes if migration is rolled back.
    """
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Reverse Event ContentType
    try:
        event_ct = ContentType.objects.get(app_label='seasons', model='event')
        event_ct.app_label = 'attendance'
        event_ct.save()
    except ContentType.DoesNotExist:
        pass
    
    # Reverse Attendance ContentType
    try:
        attendance_ct = ContentType.objects.get(app_label='seasons', model='attendance')
        attendance_ct.app_label = 'attendance'
        attendance_ct.save()
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
        ('attendance', '0004_alter_attendance_options_alter_event_options'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(update_contenttypes, reverse_contenttypes),
    ]
